# Generated by Django 4.2 on 2023-04-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_korean', models.CharField(max_length=100)),
                ('title_original', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('poster', models.URLField()),
                ('rating_percent', models.FloatField()),
                ('rating_average', models.FloatField()),
                ('rating_votes', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trailers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type', models.CharField(max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=50)),
                ('character', models.CharField(max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='movie.movie')),
            ],
        ),
    ]
